[package]
name = "lightshow-led-agent"
version = "0.1.0"
edition = "2021"

[target.arm-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[dependencies]
rs_ws281x = { version = "0.5.1", path = "/home/marc/Documents/LightShow/rpi-ws281x-rust" }
reqwest = { version = "0.11", features = ["blocking"] }
hostname = { version = "0.4" }
axum-server = { version = "0.6.0", features = ["tls-rustls"] }
axum = { version = "0.7.5" }
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }
openssl = { version = "0.10", features = ["vendored"] }
clap = { version = "4.5.20", features = ["derive"] }
